In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sc
import sklearn

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
os.chdir('C://Users/kanod/Desktop/Shamik Sir/Dataset and Code Files')

In [4]:
df_train = pd.read_csv('train_main.csv')

In [5]:
target_column = 'r/h or l/h'
target_index = df_train.columns.get_loc(target_column)

In [6]:
columns_to_keep = df_train.columns[:target_index + 1].tolist()

In [7]:
df_1 = df_train[columns_to_keep]

In [8]:
df_1.head()

,YS (MPa),UTS (MPa),K (Mpa),n,Lankford anisotropy coefficient (r),Category,Thickness,"Tool diameter (A, mm)","Step size (B, mm)",Spindle Speed (rpm),"Feed rate (D, mm/min)",Surface roughness (SR),Wall Angle (degree,r/h or l/h
0,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,4.0,0.2,2500.0,500.0,1.74,78.89,5.102
1,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,10.0,0.2,2500.0,500.0,1.45,75.11,5.102
2,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,4.0,1,2500.0,500.0,6.91,73.68,5.102
3,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,10.0,1,2500.0,500.0,3.91,68.32,5.102
4,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,10.0,0.6,2500.0,1000.0,2.66,77.63,5.102

In [9]:
df_1.shape

(501, 14)

In [10]:
df_1.dtypes

YS (MPa)                               float64
UTS (MPa)                              float64
K (Mpa)                                float64
n                                      float64
Lankford anisotropy coefficient (r)    float64
Category                                object
Thickness                              float64
Tool diameter (A, mm)                  float64
Step size (B, mm)                       object
Spindle Speed (rpm)                    float64
Feed rate (D, mm/min)                  float64
Surface roughness (SR)                 float64
Wall Angle (degree                      object
r/h or l/h                             float64
dtype: object

In [11]:
df_1.isnull().sum()

YS (MPa)                                0
UTS (MPa)                               0
K (Mpa)                                 0
n                                       0
Lankford anisotropy coefficient (r)     0
Category                                0
Thickness                               0
Tool diameter (A, mm)                   0
Step size (B, mm)                       0
Spindle Speed (rpm)                    46
Feed rate (D, mm/min)                   0
Surface roughness (SR)                  0
Wall Angle (degree                     66
r/h or l/h                             27
dtype: int64

In [12]:
# Apply target encoding on Category
encoding_map = df_1.groupby('Category')['n'].median()
df_1['Category_encoded'] = df_1['Category'].map(encoding_map)

# Get column index of Category after encoding
category_index = df_1.columns.get_loc('Category')
print("Category column index after encoding:", category_index)

Category column index after encoding: 5

In [13]:
df_1.head()

,YS (MPa),UTS (MPa),K (Mpa),n,Lankford anisotropy coefficient (r),Category,Thickness,"Tool diameter (A, mm)","Step size (B, mm)",Spindle Speed (rpm),"Feed rate (D, mm/min)",Surface roughness (SR),Wall Angle (degree,r/h or l/h,Category_encoded
0,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,4.0,0.2,2500.0,500.0,1.74,78.89,5.102,0.14
1,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,10.0,0.2,2500.0,500.0,1.45,75.11,5.102,0.14
2,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,4.0,1,2500.0,500.0,6.91,73.68,5.102,0.14
3,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,10.0,1,2500.0,500.0,3.91,68.32,5.102,0.14
4,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,10.0,0.6,2500.0,1000.0,2.66,77.63,5.102,0.14

In [14]:
df_1['Step size (B, mm)'] = df_1['Step size (B, mm)'].astype(str).str.replace(',', '.', regex = False)
df_1['Step size (B, mm)'] = df_1['Step size (B, mm)'].astype(float)

In [15]:
# from sklearn.impute import KNNImputer
# imputer = KNNImputer(n_neighbors = 3, weights = 'uniform')

In [16]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')

In [17]:
df_1['Spindle Speed (rpm)'] = imputer.fit_transform(df_1[['Spindle Speed (rpm)']])

In [18]:
df_1['Wall Angle (degree'] = df_1['Wall Angle (degree'].astype(str).str.replace(',', '.', regex = False)
df_1['Wall Angle (degree'] = df_1['Wall Angle (degree'].astype(float)

df_1['Wall Angle (degree'] = imputer.fit_transform(df_1[['Wall Angle (degree']])

In [19]:
df_1['r/h or l/h'] = imputer.fit_transform(df_1[['r/h or l/h']])

In [20]:
# df_1['MRR'] = df_1['Step size (B, mm)'] * df_1['Feed rate (D, mm/min)'] * df_1['Thickness']
# df_1['Cutting_Speed'] = (np.pi * df_1['Tool diameter (A, mm)'] * df_1['Spindle Speed (rpm)']) / 1000
# df_1['Formability_index'] = df_1['n'] * df_1['Lankford anisotropy coefficient (r)']
# df_1['Strength_ratio'] = df_1['YS (MPa)'] / df_1['UTS (MPa)']
# df_1['Work_hardening_capacity'] = df_1['K (Mpa)'] / df_1['UTS (MPa)']
# df_1['Material_toughness'] = df_1['n'] * df_1['UTS (MPa)']
# df_1['Tool_thickness_ratio'] = df_1['Tool diameter (A, mm)'] / df_1['Thickness']
# df_1['Incremental_strain_rate'] = df_1['Feed rate (D, mm/min)'] / df_1['Step size (B, mm)']

In [21]:
df_1.head()

,YS (MPa),UTS (MPa),K (Mpa),n,Lankford anisotropy coefficient (r),Category,Thickness,"Tool diameter (A, mm)","Step size (B, mm)",Spindle Speed (rpm),"Feed rate (D, mm/min)",Surface roughness (SR),Wall Angle (degree,r/h or l/h,Category_encoded
0,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,4.0,0.2,2500.0,500.0,1.74,78.89,5.102,0.14
1,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,10.0,0.2,2500.0,500.0,1.45,75.11,5.102,0.14
2,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,4.0,1.0,2500.0,500.0,6.91,73.68,5.102,0.14
3,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,10.0,1.0,2500.0,500.0,3.91,68.32,5.102,0.14
4,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,10.0,0.6,2500.0,1000.0,2.66,77.63,5.102,0.14

In [22]:
df_1 = df_1.iloc[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 14, 11, 12, 13]]

In [23]:
df_1.head()

,YS (MPa),UTS (MPa),K (Mpa),n,Lankford anisotropy coefficient (r),Category,Thickness,"Tool diameter (A, mm)","Step size (B, mm)",Spindle Speed (rpm),"Feed rate (D, mm/min)",Category_encoded,Surface roughness (SR),Wall Angle (degree,r/h or l/h
0,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,4.0,0.2,2500.0,500.0,0.14,1.74,78.89,5.102
1,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,10.0,0.2,2500.0,500.0,0.14,1.45,75.11,5.102
2,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,4.0,1.0,2500.0,500.0,0.14,6.91,73.68,5.102
3,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,10.0,1.0,2500.0,500.0,0.14,3.91,68.32,5.102
4,171.27,194.18,310.4,0.11,0.55,variable angle conical shaped part,0.7,10.0,0.6,2500.0,1000.0,0.14,2.66,77.63,5.102

In [24]:
df_1 = df_1.drop('Category', axis = 1)

In [25]:
df_1.shape

(501, 14)

In [26]:
x_train = df_1.iloc[:, :11].values
y_train = df_1.iloc[:, 11:].values

In [27]:
x_train.shape

(501, 11)

In [28]:
print(x_train)

[[1.7127e+02 1.9418e+02 3.1040e+02 ... 2.5000e+03 5.0000e+02 1.4000e-01]
 [1.7127e+02 1.9418e+02 3.1040e+02 ... 2.5000e+03 5.0000e+02 1.4000e-01]
 [1.7127e+02 1.9418e+02 3.1040e+02 ... 2.5000e+03 5.0000e+02 1.4000e-01]
 ...
 [2.4340e+02 2.7250e+02 4.4100e+02 ... 6.5000e+02 2.0000e+03 2.0000e-01]
 [2.4340e+02 2.7250e+02 4.4100e+02 ... 6.5000e+02 2.0000e+03 2.0000e-01]
 [2.4340e+02 2.7250e+02 4.4100e+02 ... 6.5000e+02 2.0000e+03 2.0000e-01]]

In [29]:
print(y_train)

[[ 1.74  78.89   5.102]
 [ 1.45  75.11   5.102]
 [ 6.91  73.68   5.102]
 ...
 [ 2.81  60.     1.   ]
 [ 2.81  60.     1.   ]
 [ 2.81  60.     1.   ]]

In [30]:
# from sklearn.model_selection import train_test_split
# x_train, x_val, y_train, y_val = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [31]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)

In [32]:
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)

In [33]:
df_test = pd.read_excel('Test.xlsx')

In [34]:
df_test.head()

,YS (MPa),UTS (MPa),K (Mpa),n,Lankford anisotropy coefficient (r),Category,Thickness,"Tool diameter (A, mm)","Step size (B, mm)",Spindle Speed (rpm),"Feed rate (D, mm/min)",Surface roughness (SR),Wall Angle (degree,r/h or l/h,height
0,232.1,328.2,559.2,0.200,1.495,variable angle conical shaped part,1.0,10,0.2,200,400,Not Known,Not Known,0.3125,48.00
1,253.1,356.9,623.9,0.226,1.495,variable angle conical shaped part,1.5,10,0.2,200,400,Not Known,Not Known,0.1923,52.00
2,232.1,328.2,559.2,0.200,1.495,variable angle conical shaped part,1.0,10,0.2,400,1400,Not Known,Not Known,0.4234,35.42
3,253.1,356.9,623.9,0.226,1.495,variable angle conical shaped part,1.5,10,0.2,400,1400,Not Known,Not Known,0.5006,39.95

In [35]:
df_height = df_test.iloc[:, 10].values
print(df_height)

[ 400  400 1400 1400]

In [36]:
df_test = df_test.drop('height', axis = 1)

In [37]:
df_test.head()

,YS (MPa),UTS (MPa),K (Mpa),n,Lankford anisotropy coefficient (r),Category,Thickness,"Tool diameter (A, mm)","Step size (B, mm)",Spindle Speed (rpm),"Feed rate (D, mm/min)",Surface roughness (SR),Wall Angle (degree,r/h or l/h
0,232.1,328.2,559.2,0.200,1.495,variable angle conical shaped part,1.0,10,0.2,200,400,Not Known,Not Known,0.3125
1,253.1,356.9,623.9,0.226,1.495,variable angle conical shaped part,1.5,10,0.2,200,400,Not Known,Not Known,0.1923
2,232.1,328.2,559.2,0.200,1.495,variable angle conical shaped part,1.0,10,0.2,400,1400,Not Known,Not Known,0.4234
3,253.1,356.9,623.9,0.226,1.495,variable angle conical shaped part,1.5,10,0.2,400,1400,Not Known,Not Known,0.5006

In [38]:
# Apply target encoding to test set using the same mapping as train
df_test['Category_encoded'] = df_test['Category'].map(encoding_map)

df_test

,YS (MPa),UTS (MPa),K (Mpa),n,Lankford anisotropy coefficient (r),Category,Thickness,"Tool diameter (A, mm)","Step size (B, mm)",Spindle Speed (rpm),"Feed rate (D, mm/min)",Surface roughness (SR),Wall Angle (degree,r/h or l/h,Category_encoded
0,232.1,328.2,559.2,0.200,1.495,variable angle conical shaped part,1.0,10,0.2,200,400,Not Known,Not Known,0.3125,0.14
1,253.1,356.9,623.9,0.226,1.495,variable angle conical shaped part,1.5,10,0.2,200,400,Not Known,Not Known,0.1923,0.14
2,232.1,328.2,559.2,0.200,1.495,variable angle conical shaped part,1.0,10,0.2,400,1400,Not Known,Not Known,0.4234,0.14
3,253.1,356.9,623.9,0.226,1.495,variable angle conical shaped part,1.5,10,0.2,400,1400,Not Known,Not Known,0.5006,0.14

In [39]:
# df_test['MRR'] = df_test['Step size (B, mm)'] * df_test['Feed rate (D, mm/min)'] * df_test['Thickness']
# df_test['Cutting_Speed'] = (np.pi * df_test['Tool diameter (A, mm)'] * df_test['Spindle Speed (rpm)']) / 1000
# df_test['Formability_index'] = df_test['n'] * df_test['Lankford anisotropy coefficient (r)']
# df_test['Strength_ratio'] = df_test['YS (MPa)'] / df_test['UTS (MPa)']
# df_test['Work_hardening_capacity'] = df_test['K (Mpa)'] / df_test['UTS (MPa)']
# df_test['Material_toughness'] = df_test['n'] * df_test['UTS (MPa)']
# df_test['Tool_thickness_ratio'] = df_test['Tool diameter (A, mm)'] / df_test['Thickness']
# df_test['Incremental_strain_rate'] = df_test['Feed rate (D, mm/min)'] / df_test['Step size (B, mm)']

In [40]:
df_test.head()

,YS (MPa),UTS (MPa),K (Mpa),n,Lankford anisotropy coefficient (r),Category,Thickness,"Tool diameter (A, mm)","Step size (B, mm)",Spindle Speed (rpm),"Feed rate (D, mm/min)",Surface roughness (SR),Wall Angle (degree,r/h or l/h,Category_encoded
0,232.1,328.2,559.2,0.200,1.495,variable angle conical shaped part,1.0,10,0.2,200,400,Not Known,Not Known,0.3125,0.14
1,253.1,356.9,623.9,0.226,1.495,variable angle conical shaped part,1.5,10,0.2,200,400,Not Known,Not Known,0.1923,0.14
2,232.1,328.2,559.2,0.200,1.495,variable angle conical shaped part,1.0,10,0.2,400,1400,Not Known,Not Known,0.4234,0.14
3,253.1,356.9,623.9,0.226,1.495,variable angle conical shaped part,1.5,10,0.2,400,1400,Not Known,Not Known,0.5006,0.14

In [41]:
df_test = df_test.iloc[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 14, 11, 12, 13]]

In [42]:
df_test.head()

,YS (MPa),UTS (MPa),K (Mpa),n,Lankford anisotropy coefficient (r),Category,Thickness,"Tool diameter (A, mm)","Step size (B, mm)",Spindle Speed (rpm),"Feed rate (D, mm/min)",Category_encoded,Surface roughness (SR),Wall Angle (degree,r/h or l/h
0,232.1,328.2,559.2,0.200,1.495,variable angle conical shaped part,1.0,10,0.2,200,400,0.14,Not Known,Not Known,0.3125
1,253.1,356.9,623.9,0.226,1.495,variable angle conical shaped part,1.5,10,0.2,200,400,0.14,Not Known,Not Known,0.1923
2,232.1,328.2,559.2,0.200,1.495,variable angle conical shaped part,1.0,10,0.2,400,1400,0.14,Not Known,Not Known,0.4234
3,253.1,356.9,623.9,0.226,1.495,variable angle conical shaped part,1.5,10,0.2,400,1400,0.14,Not Known,Not Known,0.5006

In [43]:
df_test = df_test.drop('Category', axis = 1)

In [44]:
x_test = df_test.iloc[:, :11].values
y_test = df_test.iloc[:, 11:].values

In [45]:
print(y_test)

[['Not Known' 'Not Known' 0.3125]
 ['Not Known' 'Not Known' 0.1923]
 ['Not Known' 'Not Known' 0.4234]
 ['Not Known' 'Not Known' 0.5006]]

In [46]:
y_test[:, 0:2] = np.where(y_test[:, 0:2] == 'Not Known', 0, y_test[:, 0:2])

In [47]:
y_test = y_test.astype(float)

In [48]:
print(y_test)

[[0.     0.     0.3125]
 [0.     0.     0.1923]
 [0.     0.     0.4234]
 [0.     0.     0.5006]]

In [49]:
x_test = sc_x.transform(x_test)

In [50]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(x_train, y_train)

LinearRegression()

In [51]:
LR_pred = LR.predict(x_test)

In [52]:
LR_pred_inv = sc_y.inverse_transform(LR_pred)
print(LR_pred_inv)

[[ 0.58781429 60.22754519  2.50099497]
 [ 0.60177922 57.95548777  2.56400711]
 [ 1.14845544 57.56875143  2.26054694]
 [ 1.16242037 55.29669401  2.32355908]]

In [53]:
LR_pred_inv = 1 / LR_pred_inv
print(LR_pred_inv)

[[1.70121756 0.0166037  0.39984087]
 [1.66173899 0.01725462 0.39001452]
 [0.8707347  0.01737053 0.44237082]
 [0.86027398 0.01808426 0.43037425]]

In [54]:
print(np.concatenate([LR_pred_inv[:, 2].reshape(-1, 1), y_test[:, 2].reshape(-1, 1)], axis = 1))

[[0.39984087 0.3125    ]
 [0.39001452 0.1923    ]
 [0.44237082 0.4234    ]
 [0.43037425 0.5006    ]]

In [55]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test[:, 2], LR_pred_inv[:, 2]))

0.09356298878967917

In [56]:
from sklearn.svm import SVR
from sklearn.multioutput import MultiOutputRegressor
SVR = MultiOutputRegressor(SVR(kernel = "linear", C = 100, gamma = 0.1, epsilon = 0.1))
SVR.fit(x_train, y_train)

MultiOutputRegressor(estimator=SVR(C=100, gamma=0.1, kernel='linear'))

In [57]:
SVR_pred = SVR.predict(x_test)

In [58]:
print(SVR_pred)

[[-1.4292819  -0.05470189  0.20377994]
 [-1.42589832 -0.14360127  0.26740951]
 [-1.03293804 -0.10697688  0.16791794]
 [-1.02955446 -0.19587627  0.23154752]]

In [59]:
SVR_pred_inv = sc_y.inverse_transform(SVR_pred)
print(LR_pred_inv)

[[1.70121756 0.0166037  0.39984087]
 [1.66173899 0.01725462 0.39001452]
 [0.8707347  0.01737053 0.44237082]
 [0.86027398 0.01808426 0.43037425]]

In [60]:
SVR_pred_inv = 1 / SVR_pred_inv
print(SVR_pred_inv)

[[3.16873371 0.01727045 0.44426935]
 [3.12235722 0.01765121 0.43026527]
 [1.15653656 0.01749233 0.45257132]
 [1.15030064 0.01788305 0.43804752]]

In [61]:
print(np.concatenate([SVR_pred_inv[:, 2].reshape(-1, 1), y_test[:, 2].reshape(-1, 1)], axis = 1))

[[0.44426935 0.3125    ]
 [0.43026527 0.1923    ]
 [0.45257132 0.4234    ]
 [0.43804752 0.5006    ]]

In [62]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test[:, 2], SVR_pred_inv[:, 2]))

0.11536460645968974

In [63]:
from sklearn.tree import DecisionTreeRegressor
DTR = DecisionTreeRegressor(random_state = 0)
DTR.fit(x_train, y_train)

DecisionTreeRegressor(random_state=0)

In [64]:
DTR_pred = DTR.predict(x_test)

In [65]:
DTR_pred_inv = sc_y.inverse_transform(DTR_pred)
print(DTR_pred_inv)

[[ 0.61816667 48.33333333  3.42      ]
 [ 0.61816667 48.33333333  3.42      ]
 [ 0.884      45.          3.42      ]
 [ 0.884      45.          3.42      ]]

In [66]:
DTR_pred_inv = 1 / DTR_pred_inv
print(DTR_pred_inv)

[[1.61768671 0.02068966 0.29239766]
 [1.61768671 0.02068966 0.29239766]
 [1.13122172 0.02222222 0.29239766]
 [1.13122172 0.02222222 0.29239766]]

In [67]:
print(np.concatenate([DTR_pred_inv[:, 2].reshape(-1, 1), y_test[:, 2].reshape(-1, 1)], axis = 1))

[[0.29239766 0.3125    ]
 [0.29239766 0.1923    ]
 [0.29239766 0.4234    ]
 [0.29239766 0.5006    ]]

In [68]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test[:, 2], DTR_pred_inv[:, 2]))

0.11485116959064329

In [69]:
from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators = 10, random_state = 0)
RFR.fit(x_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [70]:
RFR_pred = RFR.predict(x_test)

In [71]:
RFR_pred_inv = sc_y.inverse_transform(RFR_pred)
print(RFR_pred_inv)

[[ 2.002065   53.97133333  3.635     ]
 [ 1.99517333 54.138       3.608     ]
 [ 1.38029367 54.17133333  3.644     ]
 [ 1.32488867 54.67133333  3.608     ]]

In [72]:
RFR_pred_inv = 1 / RFR_pred_inv
print(RFR_pred_inv)

[[0.49948428 0.01852835 0.27510316]
 [0.50120959 0.01847131 0.27716186]
 [0.72448351 0.01845995 0.27442371]
 [0.7547804  0.01829112 0.27716186]]

In [73]:
print(np.concatenate([RFR_pred_inv[:, 2].reshape(-1, 1), y_test[:, 2].reshape(-1, 1)], axis = 1))

[[0.27510316 0.3125    ]
 [0.27716186 0.1923    ]
 [0.27442371 0.4234    ]
 [0.27716186 0.5006    ]]

In [74]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test[:, 2], RFR_pred_inv[:, 2]))

0.12366828152626388

In [75]:
import xgboost
from xgboost import XGBRegressor
XGBR = XGBRegressor()
XGBR.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [76]:
XGBR_pred = XGBR.predict(x_test)

In [77]:
XGBR_pred_inv = sc_y.inverse_transform(XGBR_pred)
print(XGBR_pred_inv)

[[ 1.4244609 33.331303   3.801623 ]
 [ 1.2458974 42.193962   3.7912555]
 [ 2.5252943 32.439877   3.840174 ]
 [ 2.549525  41.265408   3.8413389]]

In [78]:
XGBR_pred_inv = 1 / XGBR_pred_inv
print(XGBR_pred_inv)

[[0.70202    0.03000183 0.26304555]
 [0.8026343  0.02370007 0.26376486]
 [0.39599344 0.03082626 0.26040486]
 [0.3922299  0.02423337 0.2603259 ]]

In [79]:
print(np.concatenate([XGBR_pred_inv[:, 2].reshape(-1, 1), y_test[:, 2].reshape(-1, 1)], axis = 1))

[[0.26304555 0.3125    ]
 [0.26376486 0.1923    ]
 [0.26040486 0.4234    ]
 [0.26032591 0.5006    ]]

In [80]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test[:, 2], XGBR_pred_inv[:, 2]))

0.13104713629484177

In [81]:
import lightgbm
from lightgbm import LGBMRegressor
LGBMR = MultiOutputRegressor(LGBMRegressor(learning_rate = 0.05, n_estimators = 100))
LGBMR.fit(x_train, y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000045 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 202
[LightGBM] [Info] Number of data points in the train set: 501, number of used features: 11
[LightGBM] [Info] Start training from score 0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000098 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 202
[LightGBM] [Info] Number of data points in the train set: 501, number of used features: 11
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000096 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 202
[LightGBM] [Info] Number of data points in the train set: 501, number of used features: 11
[LightGBM] [Info] Start training from score 0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

MultiOutputRegressor(estimator=LGBMRegressor(learning_rate=0.05))

In [82]:
LGBMR_pred = LGBMR.predict(x_test)

In [83]:
LGBMR_pred_inv = sc_y.inverse_transform(LGBMR_pred)
print(LGBMR_pred_inv)

[[ 0.93916272 44.3778103   3.44882929]
 [ 0.97535072 46.10222776  3.5625453 ]
 [ 3.4801124  45.30813098  3.16466052]
 [ 3.49441474 46.73182603  3.26681153]]

In [84]:
LGBMR_pred_inv = 1 / LGBMR_pred_inv
print(LGBMR_pred_inv)

[[1.06477821 0.02253378 0.28995346]
 [1.02527222 0.02169093 0.28069819]
 [0.28734704 0.02207109 0.31598966]
 [0.28617095 0.02139869 0.30610887]]

In [85]:
print(np.concatenate([LGBMR_pred_inv[:, 2].reshape(-1, 1), y_test[:, 2].reshape(-1, 1)], axis = 1))

[[0.28995346 0.3125    ]
 [0.28069819 0.1923    ]
 [0.31598966 0.4234    ]
 [0.30610887 0.5006    ]]

In [86]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test[:, 2], LGBMR_pred_inv[:, 2]))

0.10321154663917553